name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build on merge

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create local.properties
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          BASIC_USER_NAME: ${{ secrets.BASIC_USER_NAME }}
          BASIC_PASS: ${{ secrets.BASIC_PASS }}
        run: |
          echo "BASE_URL"=${BASE_URL} >> ./local.properties
          echo "BASIC_USER_NAME"=${BASIC_USER_NAME} >> ./local.properties
          echo "BASIC_PASS"=${BASIC_PASS} >> ./local.properties

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Unit Test
        run: ./gradlew testDebug

      - name: Build with Gradle
        run: ./gradlew assembleDebug